#!/bin/sh

[ -f "packages/$1.tar.lz" ] && exit 0

rm -f "logs/$1.log.lz" "logs/$1.log" 2>/dev/null
for i in 1 2 3
do
	echo "> Building $1 (attempt $i), $(date -R)" >> "logs/$1.log"
	./scripts/try_build "$1" "packages/$1.tar.lz" >> "logs/$1.log" 2>&1
	[ 0 -ne $? ] && continue

	echo "> Successfuly built $1" >> "logs/$1.log"
	lzip -9 "logs/$1.log"
	exit 0
done

exit 1
