#!/bin/sh

# install the packages
cp -f "$2" "$1/script"
cp -r repo "$1/"
PREFIX="$1" packlim source /script
rm -rf "$1/repo" "$1/script"

# fix permissions
chown -R 0:0 "$1"
find "$1" -type d | while read directory
do
	chmod 755 "$directory"
done
chmod 700 "$1/home/boss"
chown 1000:1000 "$1/home/someone"
chmod 755 "$1/home/someone"
