#!/bin/sh

# install the packages
HERE="$(pwd)"
REPO="file://$HERE/repo" PREFIX="$1" packlim source "$2"

# fix permissions
chown -R 0:0 "$1"
find "$1" -type d | while read directory
do
	chmod 755 "$directory"
done
chmod 700 "$1/home/boss"
chown 1000:1000 "$1/home/someone"
chmod 755 "$1/home/someone"
