#!/bin/sh

./scripts/gen_deps > Makefile.deps
make -j 1
[ 0 -ne $? ] && exit 1

./scripts/create_repo

./scripts/create_iso flavors/minimal
./scripts/create_iso flavors/big
./scripts/create_iso flavors/huge
./scripts/create_tar flavors/rootfs
