#!/bin/sh

rm -rvf images/iso/* \
        images/vm/* \
        images/chroot/* \
        sysroot/* \
        logs/* \
        packages/* \
        debug/* \
        repo/* \
        *-config \
        Makefile.deps
