#!/bin/sh

# make sure the package does not contain /usr or /sbin
[ -d "$2/usr" ] && exit 1
[ -d "$2/sbin" ] && exit 1

# make sure man pages go only to /man
case "$(find "$2" -type d -name "man")" in
	""|"$2/man")
		;;

	*)
		exit 1
		;;
esac

# make sure the package documentation goes to either /doc/$1 or /share/$1
find "$2" -type d -name "doc" | while read i
do
	case "$i" in
		"$2/doc"|"$2/share/$1"/*)
			;;

		*)
			exit 1
			;;
	esac
done
[ 0 -ne $? ] && exit 1

# make sure the package has only one directory under /doc
if [ -d "$2/doc" ]
then
	cd rules
	for i in *
	do
		[ "$1" = "$i" ] && continue
		[ -d "$2/doc/$i" ] && exit 1
	done
fi

exit 0
