tty="$(readlink /proc/self/fd/0)"
case "$tty" in
	/dev/tty*)
		tty="|$(basename "$tty")"
		;;
	/dev/pts/*)
		tty="|pts$(basename "$tty")"
		;;
	*)
		tty=""
esac
export PS1="[\u$tty@\w]\$ "
unset tty
export HISTFILE="$HOME/.ksh_history"

bind '^[[1~'="beginning-of-line"
bind '^[[4~'="end-of-line"
bind '^[[3~'="delete-char-forward"
bind -m '^L'="clear^J"

alias ls="ls --color=auto"
alias ll="ls -la"
